export const ADD_USER_DATA = 'ADD_USER_DATA';
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA';
export const CLEAR_USER_DETAILS = 'CLEAR_USER_DETAILS';
export const UPDATE_DATA = 'UPDATE_DATA';
export const REMOVE_CART_DATA = 'REMOVE_CART_DATA';
